mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: xyz.labmem.Trafficviolationsystem.Entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trafficviolationsystem?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
server:
  port: 8080
